import { getUserPrefrences } from "../../../lib/preference";
import "../globals.css";

export const metadata = {
  title: "Handeling Error - Users",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const pref = await getUserPrefrences();
  console.log(pref);
  return (
    <main>
      <nav>
        <h1>Some header</h1>
      </nav>
      {children}
    </main>
  );
}
